---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: suwayomi
  name: suwayomi-pod
spec:
  containers:
    - name: suwayomi-container
      image: ghcr.io/mamotromico/suwayomi-server:latest
      ports:
        - containerPort: 4567
          hostIP: 0.0.0.0
          hostPort: 4567
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /home/suwayomi
          name: suwayomi-directory
        - mountPath: /home/suwayomi/downloads
          name: suwayomi-downloads
        - mountPath: /home/suwayomi/server.conf
          name: suwayomi-config
          subpath: server.conf
    - name: flaresolverr
      image: ghcr.io/thephaseless/byparr:latest
      env:
        - name: TZ
          value: America/Sao_Paulo
      ports:
        - containerPort: 8191
          hostIP: 0.0.0.0
          hostPort: 8191
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
  volumes:
    - name: suwayomi-directory
      hostPath:
        path: .test/data # your host directory path
        type: DirectoryOrCreate
    - name: suwayomi-downloads
      hostPath:
        path: .test/downloads
        type: DirectoryOrCreate
    - name: suwayomi-config
      configMap:
        name: suwayomi-config
  restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suwayomi-config
data:
  server.conf: |- #properties
    # Server ip and port bindings
    server.ip = "0.0.0.0"
    server.port = 4567

    # Socks5 proxy
    server.socksProxyEnabled = false
    server.socksProxyVersion = 5 # 4 or 5
    server.socksProxyHost = ""
    server.socksProxyPort = ""
    server.socksProxyUsername = ""
    server.socksProxyPassword = ""

    # webUI
    server.webUIEnabled = true
    server.initialOpenInBrowserEnabled = true
    server.webUIInterface = "browser" # "browser" or "electron"
    server.electronPath = ""
    server.webUIFlavor = "WebUI" # "WebUI" or "Custom"
    server.webUIChannel = preview # "BUNDLED" or "STABLE" or "PREVIEW"
    server.webUIUpdateCheckInterval = 23

    # downloader
    server.downloadAsCbz = true
    server.downloadsPath = ""
    server.autoDownloadNewChapters = false
    server.excludeEntryWithUnreadChapters = true
    server.autoDownloadNewChaptersLimit = 0
    server.autoDownloadIgnoreReUploads = false
    server.downloadConversions = {}

    # updater
    server.excludeUnreadChapters = true
    server.excludeNotStarted = true
    server.excludeCompleted = true
    server.globalUpdateInterval = 12
    server.updateMangas = false

    # Authentication
    server.authMode = "none" # none, basic_auth, simple_login or ui_login
    server.authUsername = "user"
    server.authPassword = "pass"
    server.jwtAudience = "suwayomi-server-api"
    server.jwtTokenExpiry = "5m"
    server.jwtRefreshExpiry = "60d"

    # misc
    server.debugLogsEnabled = false
    server.systemTrayEnabled = true
    server.maxLogFiles = 31
    server.maxLogFileSize = "10mb"
    server.maxLogFolderSize = "100mb"
    server.extensionRepos = []
    server.maxSourcesInParallel = 6

    # backup
    server.backupPath = ""
    server.backupTime = "00:00"
    server.backupInterval = 1
    server.backupTTL = 14

    # local source
    server.localSourcePath = ""

    # Cloudflare bypass
    server.flareSolverrEnabled = false
    server.flareSolverrUrl = "http://localhost:8191"
    server.flareSolverrTimeout = 60 # time in seconds
    server.flareSolverrSessionName = "suwayomi"
    server.flareSolverrSessionTtl = 15 # time in minutes
    server.flareSolverrAsResponseFallback = false

    #OPDS
    server.opdsUseBinaryFileSizes = false
    server.opdsItemsPerPage = 50
    server.opdsEnablePageReadProgress = true
    server.opdsMarkAsReadOnDownload = false
    server.opdsShowOnlyUnreadChapters = false
    server.opdsShowOnlyDownloadedChapters = false
    server.opdsChapterSortOrder = "DESC"

    #KoReader sync
    server.koreaderSyncServerUrl = "http://localhost:17200"
    server.koreaderSyncUsername = ""
    server.koreaderSyncUserkey = ""
    server.koreaderSyncDeviceId = ""
    server.koreaderSyncChecksumMethod = BINARY # BINARY or FILENAME
    server.koreaderSyncPercentageTolerance = 1.0E-15 # range: [1.0E-15, 1.0]
    server.koreaderSyncStrategyForward = PROMPT # PROMPT, KEEP_LOCAL, KEEP_REMOTE, DISABLED
    server.koreaderSyncStrategyBackward = DISABLED # PROMPT, KEEP_LOCAL, KEEP_REMOTE, DISABLED

    #Database
    server.databaseType = H2 # H2, POSTGRESQL
    server.databaseUrl = "postgresql://localhost:5432/suwayomi"
    server.databaseUsername = ""
    server.databasePassword = ""
---

