apiVersion: v1
kind: Pod
metadata:
  labels:
    app: suwayomi
  name: suwayomi-pod
spec:
  containers:
    - env:
        - name: TZ
          value: Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        # Comment these out if you do not use the flaresolverr container at the bottom of this file
        - name: FLARESOLVERR_ENABLED
          value: "true"
        - name: FLARESOLVERR_URL
          value: http://localhost:8191
  #  #################################################################################################
  #
  #    !!! IMPORTANT !!!
  #     - server settings can be changed during runtime in the WebUI
  #     - providing an environment variable will OVERWRITE the current setting value when starting the container
  #
  #  #################################################################################################
  #
  #    example for setting env vars:
  #
  #      - name: BIND_IP
  #        value: 0.0.0.0
  #      - name: BIND_PORT
  #        value: 4567
  #      - name: SOCKS_PROXY_ENABLED
  #        value: "false"
  #      - name: DOWNLOAD_AS_CBZ
  #        value: "true"
  #      - name: BASIC_AUTH_ENABLED
  #        value: "true"
  #      - name: BASIC_AUTH_USERNAME
  #        value: manga
  #      - name: BASIC_AUTH_PASSWORD
  #        value: hello123
  #      - name: EXTENSION_REPOS
  #        value: '["http://github.com/orginazation-name/repo-name", "http://github.com/orginazation-name-2/repo-name-2"]'
  #  #################################################################################################
      image: ghcr.io/suwayomi/tachidesk:latest
      name: suwayomi-container
      ports:
        - containerPort: 4567
          hostIP: 0.0.0.0
          hostPort: 4567
      volumeMounts:
        - mountPath: /home/suwayomi/.local/share/Tachidesk
          name: suwayomi-directory
    - env:
        - name: TZ
          value: America/Sao_Paulo
      image: ghcr.io/thephaseless/byparr:latest
      name: flaresolverr
      ports:
        - containerPort: 8191
          hostIP: 0.0.0.0
          hostPort: 8191
  volumes:
    - hostPath:
        path: ./data
        type: DirectoryOrCreate
      name: suwayomi-directory
