---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.infra.name: suwayomi-infra
  labels:
    app: suwayomi
  name: suwayomi
spec:
  containers:
    - name: container
      env:
        - name: TZ
          value: America/Sao_Paulo
      image: ghcr.io/mamotromico/suwayomi-server:latest
      ports:
        - containerPort: 4567
          hostPort: 4567
          protocol: tcp
      volumeMounts:        
        # - mountPath: /suwayomi/downloads
        #   name: suwayomi-downloads
        # - mountPath: /suwayomi/backups
        #   name: suwayomi-backups
        # - mountPath: /suwayomi/logs
        #   name: suwayomi-logs
        - mountPath: /suwayomi
          name: suwayomi-directory
        - mountPath: /suwayomi/server.conf
          name: suwayomi-config-file
          subPath: server.conf
          readOnly: true
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000 # Replaces usual PUID configurations
        runAsGroup: 1000 # Replaces usual PGID configurations        
  volumes:
    - name: suwayomi-config-file
      configMap:
        name: suwayomi-config 
    - name: suwayomi-directory
      hostPath:
        path: /path/to/your/data # your host directory path
        type: DirectoryOrCreate
    # - name: suwayomi-downloads
    #   hostPath:
    #     path: 
    #     type: DirectoryOrCreate
    # - name: suwayomi-backups
    #   hostPath:
    #     path: 
    #     type: DirectoryOrCreate
    # - name: suwayomi-logs
    #   hostPath:
    #     path: 
    #     type: DirectoryOrCreate  
  restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suwayomi-config
data:
  server.conf: |- #properties
    # Server ip and port bindings
    server.ip = "0.0.0.0"
    server.port = 4567

    # Socks5 proxy
    server.socksProxyEnabled = false
    server.socksProxyVersion = 5 # 4 or 5
    server.socksProxyHost = ""
    server.socksProxyPort = ""
    server.socksProxyUsername = ""
    server.socksProxyPassword = ""

    # webUI
    server.webUIEnabled = false
    server.initialOpenInBrowserEnabled = false
    server.webUIInterface = "browser" # "browser" or "electron"
    server.electronPath = ""
    server.webUIFlavor = "WebUI" # "WebUI" or "Custom"
    server.webUIChannel = STABLE # "BUNDLED" or "STABLE" or "PREVIEW"
    server.webUIUpdateCheckInterval = 23

    # downloader
    server.downloadAsCbz = false
    server.downloadsPath = ""
    server.autoDownloadNewChapters = false
    server.excludeEntryWithUnreadChapters = true
    server.autoDownloadNewChaptersLimit = 0
    server.autoDownloadIgnoreReUploads = false
    server.downloadConversions = {}

    # updater
    server.excludeUnreadChapters = true
    server.excludeNotStarted = true
    server.excludeCompleted = true
    server.globalUpdateInterval = 12
    server.updateMangas = true

    # Authentication
    server.authMode = "none" # none, basic_auth, simple_login or ui_login
    server.authUsername = "user"
    server.authPassword = "pass"
    server.jwtAudience = "suwayomi-server-api"
    server.jwtTokenExpiry = "5m"
    server.jwtRefreshExpiry = "60d"

    # misc
    server.debugLogsEnabled = false
    server.systemTrayEnabled = false
    server.maxLogFiles = 31
    server.maxLogFileSize = "10mb"
    server.maxLogFolderSize = "100mb"
    server.extensionRepos = []
    server.maxSourcesInParallel = 6

    # backup
    server.backupPath = ""
    server.backupTime = "00:00"
    server.backupInterval = 1
    server.backupTTL = 14

    # local source
    server.localSourcePath = ""

    # Cloudflare bypass
    server.flareSolverrEnabled = false
    server.flareSolverrUrl = "http://localhost:8191"
    server.flareSolverrTimeout = 60 # time in seconds
    server.flareSolverrSessionName = "suwayomi"
    server.flareSolverrSessionTtl = 15 # time in minutes
    server.flareSolverrAsResponseFallback = false

    #OPDS
    server.opdsUseBinaryFileSizes = false
    server.opdsItemsPerPage = 50
    server.opdsEnablePageReadProgress = true
    server.opdsMarkAsReadOnDownload = false
    server.opdsShowOnlyUnreadChapters = false
    server.opdsShowOnlyDownloadedChapters = false
    server.opdsChapterSortOrder = "DESC"
    server.opdsCbzMimetype = "MODERN"

    #KoReader sync
    server.koreaderSyncServerUrl = "http://localhost:17200"
    server.koreaderSyncUsername = ""
    server.koreaderSyncUserkey = ""
    server.koreaderSyncDeviceId = ""
    server.koreaderSyncChecksumMethod = BINARY # BINARY or FILENAME
    server.koreaderSyncPercentageTolerance = 1.0E-15 # range: [1.0E-15, 1.0]
    server.koreaderSyncStrategyForward = PROMPT # PROMPT, KEEP_LOCAL, KEEP_REMOTE, DISABLED
    server.koreaderSyncStrategyBackward = DISABLED # PROMPT, KEEP_LOCAL, KEEP_REMOTE, DISABLED

    #Database
    server.databaseType = H2 # H2, POSTGRESQL
    server.databaseUrl = "postgresql://localhost:5432/suwayomi"
    server.databaseUsername = ""
    server.databasePassword = ""
    server.useHikariConnectionPool = true
---